---
name: trivy

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  merge_group:
  workflow_dispatch:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  build:
    name: 'trivy scan'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy vulnerability scanner (file system)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          scan-ref: .
          format: 'json'
          scanners: 'vuln,secret,config'
          # output: report-fs.sarif

      - name: Run Trivy vulnerability scanner (config)
        uses: aquasecurity/trivy-action@0.24.0
        with:
          scan-type: 'config'
          ignore-unfixed: true
          scan-ref: .
          format: 'json'
          # output: report-config.sarif

      # - name: Upload Trivy report (fs) GitHub Security
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: report-fs.sarif
      #     category: 'fs'

      # - name: Upload Trivy report (config) GitHub Security
      #   uses: github/codeql-action/upload-sarif@v3
      #   with:
      #     sarif_file: report-config.sarif
      #     category: 'config'
